# <?php die(); ?>

## 注意：书写时，缩进不能使用 Tab，必须使用空格

#############################
# 应用程序设置
#############################

# 在这里添加应用程序需要的设置
# 这里的设置可以用 Q::ini('appini/设置名') 来读取，例如 Q::ini('appini/app_title');
allow_anonymous:        false
date_fmt:               'H:i,M-j-Y'
topic_tags:
    -       Edit survey
    -       Theme
    -       Deploy
    -       Report
    -       Comments     
passport:
    service:
        surveypie:
            url:    "http://passport.surveypie.net"
            user:   "dev"
            pass:   "abc"
    login_url:      "http://test.surveypie.net/passport/login"
    logout_url:     "http://test.surveypie.net/passport/logout"
    reg_url:        "http://test.surveypie.net/passport/register"
