# <?php die(); ?>

## 注意：书写时，缩进不能使用 Tab，必须使用空格

#############################
# 应用程序设置
#############################

# 在这里添加应用程序需要的设置
# 这里的设置可以用 Q::ini('appini/设置名') 来读取，例如 Q::ini('appini/app_title');
allow_anonymous:        false
topic_tags:
    -       问卷编辑
    -       外观编辑
    -       逻辑编辑
passport:
    service:
        surveypie:
            url:    "http://passport.diaochapai.com"
            user:   "dev"
            pass:   "abc"
    login_url:      "http://www.diaochapai.com/passport/login"
    logout_url:     "http://www.diaochapai.com/passport/logout"
    reg_url:        "http://www.diaochapai.com/passport/register"
